# Generated by Django 4.2 on 2023-04-17 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCat', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoPro', models.IntegerField(unique=True)),
                ('nombrePro', models.CharField(max_length=50)),
                ('precioPro', models.IntegerField()),
                ('fotoPro', models.FileField(blank=True, null=True, upload_to='fotos/')),
                ('categoriaPro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apptienda.categoria')),
            ],
        ),
    ]
